version: "3"
services:
  app:
    build: .
    network_mode: host
    env_file: .env
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    env_file: .env
    network_mode: host
    ports:
      - 5432:5432/tcp
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: always
volumes:
  db-data:
    driver: local